@HttpLoggingSink_HostAddress = http://localhost:62847

POST {{HttpLoggingSink_HostAddress}}/log
Content-Type: application/json
X-Api-Key: test-api-key

{
  "logLevel": "Warning",
  "logMessage": "User {UserId} performed action {Action}",
  "logSource": "TestClient",
  "logArgs": [
    12345,
    "Login"
  ]
}

###
